# Generated by Django 6.0.4 on 2026-05-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknest_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
