"""
Django settings for online_library project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bvyj!*fwn(c2oqyw1rw9ot(g@2a$gx9%j@$w_e+8a%m6qzd5n0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# تعديل ALLOWED_HOSTS لتقبل السيرفر السحابي لـ Render
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booknest_library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # إضافة WhiteNoise هنا مباشرة للتعامل مع ملفات الـ CSS والـ JS في السيرفر
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'online_library.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_library.wsgi.application'


# ==========================================================================
# إعدادات قاعدة البيانات (الربط بالقرص الدائم المحمي على Render)
# ==========================================================================
# نقوم بفحص ما إذا كان المجلد /data موجوداً (مجلد الـ Disk في Render)، وإلا نستخدم المسار المحلي الافتراضي
if os.path.exists('/data'):
    DATABASE_PATH = '/data/db.sqlite3'
else:
    DATABASE_PATH = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'booknest_library.User'
LOGIN_REDIRECT_URL = 'user_home'
LOGOUT_REDIRECT_URL = 'index'
LOGIN_URL = 'login'


# ==========================================================================
# إعدادات الملفات الثابتة والميديا (Static & Media Files)
# ==========================================================================

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# مسار تجميع ملفات الـ Static على السيرفر لتقرأها حزمة WhiteNoise كاش كاملاً
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ربط ملفات الميديا (أغلفة الكتب) بالقرص الدائم المحمي في Render لكي لا تُمسح أبداً
if os.path.exists('/data'):
    MEDIA_ROOT = '/data/media/'
else:
    MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'