"""
Django settings for online_library project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path
import dj_database_url  # مكتبة قراءة روابط PostgreSQL الخارجية

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bvyj!*fwn(c2oqyw1rw9ot(g@2a$gx9%j@$w_e+8a%m6qzd5n0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# تفعيل استقبال النطاقات لـ Vercel والمحلي
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'booknest_library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # حزمة WhiteNoise للتعامل مع ملفات الـ CSS والـ JS في Vercel
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'online_library.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_library.wsgi.application'


# ==========================================================================
# إعدادات قاعدة البيانات السحابية (Neon PostgreSQL)
# ==========================================================================
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://neondb_owner:npg_xIzKbt6kE8JM@ep-spring-bonus-apt3g5wm-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'booknest_library.User'
LOGIN_REDIRECT_URL = 'user_home'
LOGOUT_REDIRECT_URL = 'index'
LOGIN_URL = 'login'


# ==========================================================================
# إعدادات الملفات الثابتة والميديا (Static & Media Files)
# ==========================================================================

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# مسار تجميع ملفات الـ Static لـ Vercel و WhiteNoise
STATIC_ROOT = BASE_DIR / 'staticfiles'

# إعدادات الميديا الافتراضية (سيتم الاعتماد على روابط الصور الخارجية لتجنب الحذف)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'